# Test fixture for complete bundle definition
# This file tests syntax highlighting for all bundle block types together

define bundle metadata {
  class   = "terramate.io/tf-github-organization"
  version = "1.0.0"

  name         = "GitHub Organization"
  description  = <<EOF
    This Bundle creates and manages a GitHub Repository.

    Note: This bundle can only be instantiated once.

    When instantiated a single stack will be created.

    The stack will contain code generated by the terramate.io/tf-github-organization Terramate Component.
  EOF
  technologies = ["terraform", "opentofu"]
}

define bundle {
  alias = "organization"
}

define bundle {
  scaffolding {
    path  = "/stacks/bundle_organization.tm.hcl"
    label = "organization"
  }
}

define bundle {
  input "organization" {
    type                  = string
    prompt                = "The Github Organization"
    description           = <<-EOF
      The Github Organization to configure.
      Only one organization is supported to be manged in this repository.
    EOF
    required_for_scaffold = true
  }

  input "members_to_import" {
    type        = list(string)
    description = "A List of members (github usernames) to import."
    default     = []
  }

  input "members" {
    type = map(string)

    description = <<-EOF
      A map of organization members with role 'member' mapping real names to github usernames.
      The real names are used when scaffolding teams to select team members.
    EOF

    default = {}
  }

  input "owners" {
    type        = map(string)
    description = <<-EOF
      A map of organization owners (members with role 'admin/owner') mapping real names to github usernames.
      The real names are used when scaffolding teams to select team members.
    EOF

    default = {}
  }

  #### Exports

  export "organization" {
    value = tm_slug(bundle.input.organization.value)
  }

  export "all_members" {
    value = tm_merge(
      { for k, v in bundle.input.members.value : tm_slug(v) => {
        name       = k
        name_slug  = tm_slug(k)
        login      = v
        login_slug = tm_slug(v)
        role       = "member"
      } },
      { for k, v in bundle.input.owners.value : tm_slug(v) => {
        name       = k
        name_slug  = tm_slug(k)
        login      = v
        login_slug = tm_slug(v)
        role       = "admin"
      } },
    )
  }
}


