# Test fixture for bundle metadata block
# This file tests syntax highlighting for define bundle metadata

define bundle metadata {
  class   = "terramate.io/tf-github-organization"
  version = "1.0.0"

  name         = "GitHub Organization"
  description  = <<EOF
    This Bundle creates and manages a GitHub Repository.

    Note: This bundle can only be instantiated once.

    When instantiated a single stack will be created.

    The stack will contain code generated by the terramate.io/tf-github-organization Terramate Component.
  EOF
  technologies = ["terraform", "opentofu"]
}


